### ISSUE TITLE
Error build_2

### ISSUE THREAD

**Issue by motehsu** [daweileng/keras_MOD#4]
Hi, can anyone help me?
Error running model 2.

ValueError: Input dimension mis-match. (input[0].shape[0] = 42, input[1].shape[0] = 10)

**Comment by prFavors** [comment]
I have similar problem, it seems that the implementation of the CTC cost function is limited, with more cnn does not work, or modifying the convolution filter size.

**Comment by daweileng** [comment]
Seemed you gave wrong input of x_mask.

**Comment by prFavors** [comment]
I don't quite understand how the operation of the mask, as it would be for the function build2? @daweileng could you give me a hint?

**Comment by daweileng** [comment]
Please provide your code and the error trace back message. The mask is for handling samples with different lengths.

**Comment by prFavors** [comment]
Thanks for listening @daweileng 

The example is just that:
[https://github.com/daweileng/keras_MOD/blob/master/demo/mnist_ctc_v9.py](url)


I'm changing the build function.
My idea is basically include more layers of convolutions and sub samples in order to understand and find the best parameters. So I'm using this to test this:

`def build_modelCustom(feadim, Nclass, loss='ctc_cost_for_train', optimizer='Adadelta'):
    net_input = Input(shape=(1, feadim, None))
    net_cnn   = Convolution2D(16, 3, 3, activation='relu', border_mode='valid')(net_input)
    pool1  = MaxPooling2D(pool_size=(2, 2), name='pool1')(net_cnn)

    net_cnn2 = Convolution2D(32, 3, 3, activation='relu', border_mode='valid')(pool1)
    pool2 = MaxPooling2D(pool_size=(2, 2), name='pool2')(net_cnn2)

    net_reshape = Permute((3,2))(pool2)
    net_o1    = LSTM(100, return_sequences=True, activation='tanh')(net_reshape)
    net_ad1   = LSTM(100, return_sequences=True, activation='tanh', go_backwards=True)(net_o1)
    net_o2    = TimeDistributed(Dense(Nclass + 1,  activation='softmax'))(net_ad1)
    model     = Model(net_input, net_o2)
    model.compile(loss=loss, optimizer=optimizer, sample_weight_mode='temporal')

    print(model.summary())
    return model
 `

  And below is the error generated:

`Traceback (most recent call last):
  File "/home/paul_rich/anaconda3/lib/python3.5/site-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
ValueError: Dimension 1 in Rebroadcast's input was supposed to be 1 (got 32 instead)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paul_rich/Documentos/project_keras/SemRotulacao/mnist_ctc_v9.py", line 214, in <module>
    sm_mask=traindata_mask, return_sm=True)
  File "/home/paul_rich/anaconda3/lib/python3.5/site-packages/Keras-1.0.6-py3.5.egg/keras/engine/training.py", line 1315, in train_on_batch
    outputs = self.train_function[name](ins)
  File "/home/paul_rich/anaconda3/lib/python3.5/site-packages/Keras-1.0.6-py3.5.egg/keras/backend/theano_backend.py", line 616, in __call__
    return self.function(*inputs)
  File "/home/paul_rich/anaconda3/lib/python3.5/site-packages/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/paul_rich/anaconda3/lib/python3.5/site-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/paul_rich/anaconda3/lib/python3.5/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/paul_rich/anaconda3/lib/python3.5/site-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
ValueError: Dimension 1 in Rebroadcast's input was supposed to be 1 (got 32 instead)
Apply node that caused the error: Rebroadcast{?,1}(Pool{ds=(2, 2), ignore_border=True, st=(2, 2), padding=(0, 0), mode='max'}.0)
Toposort index: 258
Inputs types: [TensorType(float32, 4D)]
Inputs shapes: [(10, 32, 5, 40)]
Inputs strides: [(25600, 800, 160, 4)]
Inputs values: ['not shown']
Outputs clients: [[InplaceDimShuffle{0,3,2}(Rebroadcast{?,1}.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "/home/paul_rich/Documentos/project_keras/SemRotulacao/mnist_ctc_v9.py", line 162, in <module>
    model = build_modelCustom(feadim=28, Nclass=10, loss=loss, optimizer=optimizer)
  File "/home/paul_rich/Documentos/project_keras/SemRotulacao/mnist_ctc_v9.py", line 54, in build_modelCustom
    net_reshape = Permute((3,2))(pool2)
  File "/home/paul_rich/anaconda3/lib/python3.5/site-packages/Keras-1.0.6-py3.5.egg/keras/engine/topology.py", line 487, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/home/paul_rich/anaconda3/lib/python3.5/site-packages/Keras-1.0.6-py3.5.egg/keras/engine/topology.py", line 545, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/home/paul_rich/anaconda3/lib/python3.5/site-packages/Keras-1.0.6-py3.5.egg/keras/engine/topology.py", line 148, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/home/paul_rich/anaconda3/lib/python3.5/site-packages/Keras-1.0.6-py3.5.egg/keras/layers/core.py", line 280, in call
    return K.permute_dimensions(x, (0,) + self.dims)
  File "/home/paul_rich/anaconda3/lib/python3.5/site-packages/Keras-1.0.6-py3.5.egg/keras/backend/theano_backend.py", line 390, in permute_dimensions
    x = T.addbroadcast(x, *bcaxis)

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
`

**Comment by prFavors** [comment]
For this model 1 ,  the shape of the Mask is (10,168)

> 
____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
====================================================================================================
input_1 (InputLayer)             (None, 1, 28, None)   0                                            
____________________________________________________________________________________________________
convolution2d_1 (Convolution2D)  (None, 1, 26, None)   10          input_1[0][0]                    
____________________________________________________________________________________________________
permute_1 (Permute)              (None, None, 26)      0           convolution2d_1[0][0]            
____________________________________________________________________________________________________
lstm_1 (LSTM)                    (None, None, 100)     50800       permute_1[0][0]                  
____________________________________________________________________________________________________
timedistributed_1 (TimeDistribute(None, None, 11)      1111        lstm_1[0][0]                     
====================================================================================================
Total params: 51921
____________________________________________________________________________________________________

E para esse outro model:

> ____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
====================================================================================================
input_1 (InputLayer)             (None, 1, 28, None)   0                                            
____________________________________________________________________________________________________
convolution2d_1 (Convolution2D)  (None, 1, 26, None)   10          input_1[0][0]                    
____________________________________________________________________________________________________
pool1 (MaxPooling2D)             (None, 1, 13, None)   0           convolution2d_1[0][0]            
____________________________________________________________________________________________________
permute_1 (Permute)              (None, None, 13)      0           pool1[0][0]                      
____________________________________________________________________________________________________
lstm_1 (LSTM)                    (None, None, 100)     45600       permute_1[0][0]                  
____________________________________________________________________________________________________
timedistributed_1 (TimeDistribute(None, None, 11)      1111        lstm_1[0][0]                     
====================================================================================================
Total params: 46721
____________________________________________________________________________________________________

Changing the model 1, I have the following model


> ____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
====================================================================================================
input_1 (InputLayer)             (None, 1, 28, None)   0                                            
____________________________________________________________________________________________________
convolution2d_1 (Convolution2D)  (None, 1, 26, None)   10          input_1[0][0]                    
____________________________________________________________________________________________________
pool1 (MaxPooling2D)             (None, 1, 13, None)   0           convolution2d_1[0][0]            
____________________________________________________________________________________________________
permute_1 (Permute)              (None, None, 13)      0           pool1[0][0]                      
____________________________________________________________________________________________________
lstm_1 (LSTM)                    (None, None, 100)     45600       permute_1[0][0]                  
____________________________________________________________________________________________________
timedistributed_1 (TimeDistribute(None, None, 11)      1111        lstm_1[0][0]                     
====================================================================================================
Total params: 46721
____________________________________________________________________________________________________


What would my Mask in this case?

**Comment by daweileng** [comment]
The problem rises from this line
`net_cnn2 = Convolution2D(32, 3, 3, activation='relu', border_mode='valid')(pool1)`
In the demo code, the CNN sub-net is connected to the RNN sub-net via `permute` class as 
`net_reshape = Permute((3,2))(pool2)`
This line actually functions as re-shaping the output shape of CNN to fit the input shape of RNN, which requires the number of channel of CNN's output must be 1.To solve this, you can add another CNN layer which output only one channel.
